export const mockProducts = [
  {
    id: '1',
    name: 'Porta-Retratos Geométrico',
    slug: 'porta-retratos-geometrico',
    sku: 'PRG-001',
    shortDescription: 'Porta-retratos moderno com design geométrico, perfeito para escritório ou sala.',
    description: '<p>Porta-retratos impresso em 3D com design geométrico moderno. Ideal para exposição de fotos pequenas e médias.</p><p><strong>Especificações:</strong></p><ul><li>Material: PLA premium</li><li>Tamanho: 15x20cm</li><li>Acabamento: Fosco</li></ul>',
    price: 89.90,
    compareAtPrice: 119.90,
    status: 'published',
    isActive: true,
    isFeatured: true,
    isPersonalizable: true,
    productionTimeMinDays: 2,
    productionTimeMaxDays: 4,
    weightGrams: 150,
    widthCm: 15,
    heightCm: 20,
    depthCm: 2,
    categoryId: '1',
    category: { id: '1', name: 'Decoração', slug: 'decoracao', description: null, seoTitle: null, seoDescription: null, sortOrder: 1, isActive: true, createdAt: new Date(), updatedAt: new Date() },
    images: [
      { id: '1', productId: '1', url: 'https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=800', alt: 'Porta-retratos geométrico', sortOrder: 0, isMain: true },
    ],
    variants: [],
    personalizationFields: [
      { id: 'pf1', productId: '1', label: 'Texto para gravação', fieldType: 'text', placeholder: 'Ex: "Família Silva"', helpText: 'Máximo 30 caracteres', isRequired: true, minLength: 1, maxLength: 30, sortOrder: 0 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Suporte para Tablets',
    slug: 'suporte-tablets',
    sku: 'ST-001',
    shortDescription: 'Suporte ajustável para tablets e celulares em múltiplos ângulos.',
    description: '<p>Suporte resistente para tablets e smartphones. Design minimalista que combina com qualquer ambiente.</p>',
    price: 59.90,
    compareAtPrice: null,
    status: 'published',
    isActive: true,
    isFeatured: true,
    isPersonalizable: false,
    productionTimeMinDays: 1,
    productionTimeMaxDays: 2,
    weightGrams: 200,
    widthCm: 12,
    heightCm: 10,
    depthCm: 8,
    categoryId: '2',
    category: { id: '2', name: 'Escritório', slug: 'escritorio', description: null, seoTitle: null, seoDescription: null, sortOrder: 2, isActive: true, createdAt: new Date(), updatedAt: new Date() },
    images: [
      { id: '2', productId: '2', url: 'https://images.unsplash.com/photo-1589254065878-42c9da9e2f58?w=800', alt: 'Suporte para tablets', sortOrder: 0, isMain: true },
    ],
    variants: [
      { id: 'v1', productId: '2', name: 'Preto', sku: 'ST-001-PT', priceDelta: 0 },
      { id: 'v2', productId: '2', name: 'Branco', sku: 'ST-001-BR', priceDelta: 0 },
    ],
    personalizationFields: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Organizador de Cozinha',
    slug: 'organizador-cozinha',
    sku: 'OC-001',
    shortDescription: 'Organizador modular para temperos e utensílios pequenos.',
    description: '<p>Conjunto de organizadores modulares para cozinha. Perfeito para temperos, utensílios e objetos pequenos.</p>',
    price: 79.90,
    compareAtPrice: null,
    status: 'published',
    isActive: true,
    isFeatured: false,
    isPersonalizable: true,
    productionTimeMinDays: 2,
    productionTimeMaxDays: 3,
    weightGrams: 180,
    widthCm: 20,
    heightCm: 8,
    depthCm: 8,
    categoryId: '3',
    category: { id: '3', name: 'Cozinha', slug: 'cozinha', description: null, seoTitle: null, seoDescription: null, sortOrder: 3, isActive: true, createdAt: new Date(), updatedAt: new Date() },
    images: [
      { id: '3', productId: '3', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800', alt: 'Organizador de cozinha', sortOrder: 0, isMain: true },
    ],
    variants: [],
    personalizationFields: [
      { id: 'pf2', productId: '3', label: 'Nome da família', fieldType: 'text', placeholder: 'Ex: Família Oliveira', helpText: null, isRequired: false, minLength: null, maxLength: 25, sortOrder: 0 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Porta-retratos Pet',
    slug: 'porta-retratos-pet',
    sku: 'PRP-001',
    shortDescription: 'Porta-retratos especial para fotos dos seus pets com nome gravado.',
    description: '<p>Porta-retratos dedicado aos amigos peludos. Inclui suporte para nome do pet.</p>',
    price: 69.90,
    compareAtPrice: 89.90,
    status: 'published',
    isActive: true,
    isFeatured: true,
    isPersonalizable: true,
    productionTimeMinDays: 2,
    productionTimeMaxDays: 3,
    weightGrams: 120,
    widthCm: 15,
    heightCm: 15,
    depthCm: 2,
    categoryId: '4',
    category: { id: '4', name: 'Pets', slug: 'pets', description: null, seoTitle: null, seoDescription: null, sortOrder: 4, isActive: true, createdAt: new Date(), updatedAt: new Date() },
    images: [
      { id: '4', productId: '4', url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800', alt: 'Porta-retratos pet', sortOrder: 0, isMain: true },
    ],
    variants: [],
    personalizationFields: [
      { id: 'pf3', productId: '4', label: 'Nome do pet', fieldType: 'text', placeholder: 'Ex: Thor', helpText: null, isRequired: true, minLength: 1, maxLength: 20, sortOrder: 0 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Decoração Minimalista',
    slug: 'decoracao-minimalista',
    sku: 'DM-001',
    shortDescription: 'Conjunto de peças decorativasminimalistas para ambientação.',
    description: '<p>Conjunto de 3 peças decorativas em estilo minimalista. Perfeito para dar toque especial à qualquer ambiente.</p>',
    price: 129.90,
    compareAtPrice: null,
    status: 'published',
    isActive: true,
    isFeatured: false,
    isPersonalizable: false,
    productionTimeMinDays: 3,
    productionTimeMaxDays: 5,
    weightGrams: 300,
    widthCm: 10,
    heightCm: 20,
    depthCm: 5,
    categoryId: '1',
    category: { id: '1', name: 'Decoração', slug: 'decoracao', description: null, seoTitle: null, seoDescription: null, sortOrder: 1, isActive: true, createdAt: new Date(), updatedAt: new Date() },
    images: [
      { id: '5', productId: '5', url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', alt: 'Decoração minimalista', sortOrder: 0, isMain: true },
    ],
    variants: [],
    personalizationFields: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]